syntax = "proto3";

option go_package = 'github.com/MamangRust/microservice-payment-gateway-grpc/pb/stats/topup';

package pb.stats.topup;

import "topup/topup.proto";

message TopupMonthMethodResponse {
  string month = 1;
  string topup_method = 2;
  int32 total_topups = 3;
  int64 total_amount = 4;
}

message TopupYearlyMethodResponse {
  string year = 1;
  string topup_method = 2;
  int32 total_topups = 3;
  int64 total_amount = 4;
}

message ApiResponseTopupMonthMethod {
  string status = 1;
  string message = 2;
  repeated TopupMonthMethodResponse data = 3;
}

message ApiResponseTopupYearMethod {
  string status = 1;
  string message = 2;
  repeated TopupYearlyMethodResponse data = 3;
}

service TopupStatsMethodService {
  rpc FindMonthlyTopupMethods(pb.topup.FindYearTopupStatus)
      returns (ApiResponseTopupMonthMethod) {}
  rpc FindYearlyTopupMethods(pb.topup.FindYearTopupStatus)
      returns (ApiResponseTopupYearMethod) {}
  rpc FindMonthlyTopupMethodsByCardNumber(pb.topup.FindYearTopupCardNumber)
      returns (ApiResponseTopupMonthMethod) {}
  rpc FindYearlyTopupMethodsByCardNumber(pb.topup.FindYearTopupCardNumber)
      returns (ApiResponseTopupYearMethod) {}
}