syntax = "proto3";

option go_package = 'github.com/MamangRust/microservice-payment-gateway-grpc/pb/stats/saldo';

package pb.stats.saldo;

import "saldo/saldo.proto";

message SaldoMonthTotalBalanceResponse {
  string month = 1;
  string year = 2;
  int64 total_balance = 3;
}

message SaldoYearTotalBalanceResponse {
  string year = 1;
  int64 total_balance = 2;
}

message ApiResponseMonthTotalSaldo {
  string status = 1;
  string message = 2;
  repeated SaldoMonthTotalBalanceResponse data = 3;
}

message ApiResponseYearTotalSaldo {
  string status = 1;
  string message = 2;
  repeated SaldoYearTotalBalanceResponse data = 3;
}

service SaldoStatsTotalBalance {
  rpc FindMonthlyTotalSaldoBalance(pb.saldo.FindMonthlySaldoTotalBalance)
      returns (ApiResponseMonthTotalSaldo) {}
  rpc FindYearTotalSaldoBalance(pb.saldo.FindYearlySaldo)
      returns (ApiResponseYearTotalSaldo) {}
}