apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-writer
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-writer
  template:
    metadata:
      labels:
        app: stats-writer
    spec:
      serviceAccountName: app
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
             - |
               echo "[INIT] Waiting for Kafka to be ready (TCP)..."
               until nc -z kafka.payment-gateway.svc.cluster.local 9092; do
                 echo "Kafka is not ready yet. Retrying in 5 seconds..."
                 sleep 5
               done
               echo "[INIT] Kafka is ready!"
        - name: wait-for-redis-cluster
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Waiting for Redis Cluster nodes to be ready..."
              until nc -z redis-0.redis.payment-gateway.svc.cluster.local 6379; do
                echo "Redis Cluster node 0 is not ready yet. Retrying in 5 seconds..."
                sleep 5
              done
              echo "[INIT] Redis Cluster is accessible!"
        - name: wait-for-clickhouse
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Waiting for ClickHouse to be ready (HTTP)..."
              until nc -z clickhouse.payment-gateway.svc.cluster.local 8123; do
                echo "ClickHouse is not ready yet. Retrying in 5 seconds..."
                sleep 5
              done
              echo "[INIT] ClickHouse is accessible!"
      containers:
        - name: stats-writer
          image: ghcr.io/__GHCR_OWNER__/microservice-payment-gateway-grpc/stats-writer:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
