apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 15 workload aplikasi, satu folder per service.
resources:
  - apigateway
  - auth
  - role
  - user
  - card
  - merchant
  - saldo
  - topup
  - transaction
  - transfer
  - withdraw
  - email
  - ai-security
  - stats-reader
  - stats-writer
