syntax = "proto3";

package pb.stats.merchant;

option go_package = 'github.com/MamangRust/microservice-payment-gateway-grpc/pb/stats/merchant';

import "merchant/merchant.proto";

message MerchantResponseMonthlyTotalAmount {
  string month = 1;
  string year = 2;
  int64 total_amount = 3;
}

message MerchantResponseYearlyTotalAmount {
  string year = 1;
  int64 total_amount = 2;
}

message ApiResponseMerchantMonthlyTotalAmount {
  string status = 1;
  string message = 2;
  repeated MerchantResponseMonthlyTotalAmount data = 3;
}

message ApiResponseMerchantYearlyTotalAmount {
  string status = 1;
  string message = 2;
  repeated MerchantResponseYearlyTotalAmount data = 3;
}

service MerchantStatsTotalAmountService {
  rpc FindMonthlyTotalAmountMerchant(pb.merchant.FindYearMerchant)
      returns (ApiResponseMerchantMonthlyTotalAmount) {}
  rpc FindYearlyTotalAmountMerchant(pb.merchant.FindYearMerchant)
      returns (ApiResponseMerchantYearlyTotalAmount) {}
  rpc FindMonthlyTotalAmountByMerchants(pb.merchant.FindYearMerchantById)
      returns (ApiResponseMerchantMonthlyTotalAmount) {}
  rpc FindYearlyTotalAmountByMerchants(pb.merchant.FindYearMerchantById)
      returns (ApiResponseMerchantYearlyTotalAmount) {}
  rpc FindMonthlyTotalAmountByApikey(pb.merchant.FindYearMerchantByApikey)
      returns (ApiResponseMerchantMonthlyTotalAmount) {}
  rpc FindYearlyTotalAmountByApikey(pb.merchant.FindYearMerchantByApikey)
      returns (ApiResponseMerchantYearlyTotalAmount) {}
}