apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-financial
  namespace: payment-gateway
spec:
  serviceName: "postgres-financial"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-financial
  template:
    metadata:
      labels:
        app: postgres-financial
        tier: postgres
    spec:
      serviceAccountName: app
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: pg_financial
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "pg_financial"]
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-financial
  namespace: payment-gateway
spec:
  selector:
    app: postgres-financial
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None
