// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user_role/user_role.proto

package user_role

import (
	role "github.com/MamangRust/microservice-payment-gateway-grpc/pb/role"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRoleRequest) Reset() {
	*x = CreateUserRoleRequest{}
	mi := &file_user_role_user_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRoleRequest) ProtoMessage() {}

func (x *CreateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_role_user_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_role_user_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateUserRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type DeleteUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRoleRequest) Reset() {
	*x = DeleteUserRoleRequest{}
	mi := &file_user_role_user_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRoleRequest) ProtoMessage() {}

func (x *DeleteUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_role_user_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_role_user_role_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteUserRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteUserRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type FindByIdUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdUserRoleRequest) Reset() {
	*x = FindByIdUserRoleRequest{}
	mi := &file_user_role_user_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdUserRoleRequest) ProtoMessage() {}

func (x *FindByIdUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_role_user_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdUserRoleRequest.ProtoReflect.Descriptor instead.
func (*FindByIdUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_role_user_role_proto_rawDescGZIP(), []int{2}
}

func (x *FindByIdUserRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_user_role_user_role_proto protoreflect.FileDescriptor

const file_user_role_user_role_proto_rawDesc = "" +
	"\n" +
	"\x19user_role/user_role.proto\x12\fpb.user_role\x1a\x0frole/role.proto\"I\n" +
	"\x15CreateUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"I\n" +
	"\x15DeleteUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"2\n" +
	"\x17FindByIdUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId2\x8b\x02\n" +
	"\x0fUserRoleService\x12Q\n" +
	"\x0eCreateUserRole\x12#.pb.user_role.CreateUserRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12Q\n" +
	"\x0eDeleteUserRole\x12#.pb.user_role.DeleteUserRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12R\n" +
	"\fFindByUserId\x12%.pb.user_role.FindByIdUserRoleRequest\x1a\x19.pb.role.ApiResponsesRole\"\x00BFZDgithub.com/MamangRust/microservice-payment-gateway-grpc/pb/user_roleb\x06proto3"

var (
	file_user_role_user_role_proto_rawDescOnce sync.Once
	file_user_role_user_role_proto_rawDescData []byte
)

func file_user_role_user_role_proto_rawDescGZIP() []byte {
	file_user_role_user_role_proto_rawDescOnce.Do(func() {
		file_user_role_user_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_role_user_role_proto_rawDesc), len(file_user_role_user_role_proto_rawDesc)))
	})
	return file_user_role_user_role_proto_rawDescData
}

var file_user_role_user_role_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_role_user_role_proto_goTypes = []any{
	(*CreateUserRoleRequest)(nil),   // 0: pb.user_role.CreateUserRoleRequest
	(*DeleteUserRoleRequest)(nil),   // 1: pb.user_role.DeleteUserRoleRequest
	(*FindByIdUserRoleRequest)(nil), // 2: pb.user_role.FindByIdUserRoleRequest
	(*role.ApiResponseRole)(nil),    // 3: pb.role.ApiResponseRole
	(*role.ApiResponsesRole)(nil),   // 4: pb.role.ApiResponsesRole
}
var file_user_role_user_role_proto_depIdxs = []int32{
	0, // 0: pb.user_role.UserRoleService.CreateUserRole:input_type -> pb.user_role.CreateUserRoleRequest
	1, // 1: pb.user_role.UserRoleService.DeleteUserRole:input_type -> pb.user_role.DeleteUserRoleRequest
	2, // 2: pb.user_role.UserRoleService.FindByUserId:input_type -> pb.user_role.FindByIdUserRoleRequest
	3, // 3: pb.user_role.UserRoleService.CreateUserRole:output_type -> pb.role.ApiResponseRole
	3, // 4: pb.user_role.UserRoleService.DeleteUserRole:output_type -> pb.role.ApiResponseRole
	4, // 5: pb.user_role.UserRoleService.FindByUserId:output_type -> pb.role.ApiResponsesRole
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_role_user_role_proto_init() }
func file_user_role_user_role_proto_init() {
	if File_user_role_user_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_role_user_role_proto_rawDesc), len(file_user_role_user_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_role_user_role_proto_goTypes,
		DependencyIndexes: file_user_role_user_role_proto_depIdxs,
		MessageInfos:      file_user_role_user_role_proto_msgTypes,
	}.Build()
	File_user_role_user_role_proto = out.File
	file_user_role_user_role_proto_goTypes = nil
	file_user_role_user_role_proto_depIdxs = nil
}
