apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: card-netpol
  namespace: payment-gateway
spec:
  podSelector:
    matchLabels:
      app: card
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: payment-gateway
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: payment-gateway
