apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Edge reverse proxy di depan apigateway.
resources:
  - nginx-configmap.yaml # ConfigMap nginx-config
  - nginx-deployment.yaml # Deployment nginx
  - nginx-service.yaml # Service nginx (LoadBalancer :80)
