// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: topup/topup.proto

package topup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByIdTopupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopupId       int32                  `protobuf:"varint,1,opt,name=topup_id,json=topupId,proto3" json:"topup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdTopupRequest) Reset() {
	*x = FindByIdTopupRequest{}
	mi := &file_topup_topup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdTopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdTopupRequest) ProtoMessage() {}

func (x *FindByIdTopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdTopupRequest.ProtoReflect.Descriptor instead.
func (*FindByIdTopupRequest) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{0}
}

func (x *FindByIdTopupRequest) GetTopupId() int32 {
	if x != nil {
		return x.TopupId
	}
	return 0
}

type FindMonthlyTopupStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMonthlyTopupStatus) Reset() {
	*x = FindMonthlyTopupStatus{}
	mi := &file_topup_topup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMonthlyTopupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMonthlyTopupStatus) ProtoMessage() {}

func (x *FindMonthlyTopupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMonthlyTopupStatus.ProtoReflect.Descriptor instead.
func (*FindMonthlyTopupStatus) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{1}
}

func (x *FindMonthlyTopupStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindMonthlyTopupStatus) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearTopupStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTopupStatus) Reset() {
	*x = FindYearTopupStatus{}
	mi := &file_topup_topup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTopupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTopupStatus) ProtoMessage() {}

func (x *FindYearTopupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTopupStatus.ProtoReflect.Descriptor instead.
func (*FindYearTopupStatus) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{2}
}

func (x *FindYearTopupStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindMonthlyTopupStatusCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMonthlyTopupStatusCardNumber) Reset() {
	*x = FindMonthlyTopupStatusCardNumber{}
	mi := &file_topup_topup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMonthlyTopupStatusCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMonthlyTopupStatusCardNumber) ProtoMessage() {}

func (x *FindMonthlyTopupStatusCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMonthlyTopupStatusCardNumber.ProtoReflect.Descriptor instead.
func (*FindMonthlyTopupStatusCardNumber) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{3}
}

func (x *FindMonthlyTopupStatusCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindMonthlyTopupStatusCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindMonthlyTopupStatusCardNumber) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearTopupStatusCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTopupStatusCardNumber) Reset() {
	*x = FindYearTopupStatusCardNumber{}
	mi := &file_topup_topup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTopupStatusCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTopupStatusCardNumber) ProtoMessage() {}

func (x *FindYearTopupStatusCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTopupStatusCardNumber.ProtoReflect.Descriptor instead.
func (*FindYearTopupStatusCardNumber) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{4}
}

func (x *FindYearTopupStatusCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindYearTopupStatusCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindByCardNumberTopupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByCardNumberTopupRequest) Reset() {
	*x = FindByCardNumberTopupRequest{}
	mi := &file_topup_topup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByCardNumberTopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByCardNumberTopupRequest) ProtoMessage() {}

func (x *FindByCardNumberTopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByCardNumberTopupRequest.ProtoReflect.Descriptor instead.
func (*FindByCardNumberTopupRequest) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{5}
}

func (x *FindByCardNumberTopupRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindByCardNumberTopupRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearTopupCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTopupCardNumber) Reset() {
	*x = FindYearTopupCardNumber{}
	mi := &file_topup_topup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTopupCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTopupCardNumber) ProtoMessage() {}

func (x *FindYearTopupCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTopupCardNumber.ProtoReflect.Descriptor instead.
func (*FindYearTopupCardNumber) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{6}
}

func (x *FindYearTopupCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindYearTopupCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type TopupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	TopupNo       string                 `protobuf:"bytes,3,opt,name=topup_no,json=topupNo,proto3" json:"topup_no,omitempty"`
	TopupAmount   int64                  `protobuf:"varint,4,opt,name=topup_amount,json=topupAmount,proto3" json:"topup_amount,omitempty"`
	TopupMethod   string                 `protobuf:"bytes,5,opt,name=topup_method,json=topupMethod,proto3" json:"topup_method,omitempty"`
	TopupTime     string                 `protobuf:"bytes,6,opt,name=topup_time,json=topupTime,proto3" json:"topup_time,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupResponse) Reset() {
	*x = TopupResponse{}
	mi := &file_topup_topup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupResponse) ProtoMessage() {}

func (x *TopupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupResponse.ProtoReflect.Descriptor instead.
func (*TopupResponse) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{7}
}

func (x *TopupResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopupResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *TopupResponse) GetTopupNo() string {
	if x != nil {
		return x.TopupNo
	}
	return ""
}

func (x *TopupResponse) GetTopupAmount() int64 {
	if x != nil {
		return x.TopupAmount
	}
	return 0
}

func (x *TopupResponse) GetTopupMethod() string {
	if x != nil {
		return x.TopupMethod
	}
	return ""
}

func (x *TopupResponse) GetTopupTime() string {
	if x != nil {
		return x.TopupTime
	}
	return ""
}

func (x *TopupResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TopupResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TopupResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber    string                  `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	TopupNo       string                  `protobuf:"bytes,3,opt,name=topup_no,json=topupNo,proto3" json:"topup_no,omitempty"`
	TopupAmount   int64                   `protobuf:"varint,4,opt,name=topup_amount,json=topupAmount,proto3" json:"topup_amount,omitempty"`
	TopupMethod   string                  `protobuf:"bytes,5,opt,name=topup_method,json=topupMethod,proto3" json:"topup_method,omitempty"`
	TopupTime     string                  `protobuf:"bytes,6,opt,name=topup_time,json=topupTime,proto3" json:"topup_time,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupResponseDeleteAt) Reset() {
	*x = TopupResponseDeleteAt{}
	mi := &file_topup_topup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupResponseDeleteAt) ProtoMessage() {}

func (x *TopupResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*TopupResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{8}
}

func (x *TopupResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopupResponseDeleteAt) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *TopupResponseDeleteAt) GetTopupNo() string {
	if x != nil {
		return x.TopupNo
	}
	return ""
}

func (x *TopupResponseDeleteAt) GetTopupAmount() int64 {
	if x != nil {
		return x.TopupAmount
	}
	return 0
}

func (x *TopupResponseDeleteAt) GetTopupMethod() string {
	if x != nil {
		return x.TopupMethod
	}
	return ""
}

func (x *TopupResponseDeleteAt) GetTopupTime() string {
	if x != nil {
		return x.TopupTime
	}
	return ""
}

func (x *TopupResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TopupResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TopupResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseTopup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TopupResponse         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTopup) Reset() {
	*x = ApiResponseTopup{}
	mi := &file_topup_topup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTopup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTopup) ProtoMessage() {}

func (x *ApiResponseTopup) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTopup.ProtoReflect.Descriptor instead.
func (*ApiResponseTopup) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseTopup) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTopup) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTopup) GetData() *TopupResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTopupDeleteAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TopupResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTopupDeleteAt) Reset() {
	*x = ApiResponseTopupDeleteAt{}
	mi := &file_topup_topup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTopupDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTopupDeleteAt) ProtoMessage() {}

func (x *ApiResponseTopupDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_topup_topup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTopupDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseTopupDeleteAt) Descriptor() ([]byte, []int) {
	return file_topup_topup_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseTopupDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTopupDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTopupDeleteAt) GetData() *TopupResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_topup_topup_proto protoreflect.FileDescriptor

var file_topup_topup_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x2f, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x2e, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a,
	0x14, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x49, 0x64,
	0x22, 0x42, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x54,
	0x6f, 0x70, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x6f, 0x6e, 0x74, 0x68, 0x22, 0x29, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x59, 0x65, 0x61, 0x72,
	0x54, 0x6f, 0x70, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x79,
	0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22,
	0x6d, 0x0a, 0x20, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x54, 0x6f,
	0x70, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x22, 0x54,
	0x0a, 0x1d, 0x46, 0x69, 0x6e, 0x64, 0x59, 0x65, 0x61, 0x72, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x22, 0x53, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x43, 0x61,
	0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x4e, 0x0a, 0x17, 0x46, 0x69, 0x6e,
	0x64, 0x59, 0x65, 0x61, 0x72, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0xfe, 0x01, 0x0a, 0x0d, 0x54, 0x6f,
	0x70, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x6f, 0x70, 0x75, 0x70, 0x5f, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x6f, 0x70, 0x75, 0x70, 0x4e, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x70, 0x75, 0x70,
	0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74,
	0x6f, 0x70, 0x75, 0x70, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f,
	0x70, 0x75, 0x70, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc3, 0x02, 0x0a, 0x15, 0x54,
	0x6f, 0x70, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x5f, 0x6e,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x4e, 0x6f,
	0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x5f, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x75, 0x70,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x75,
	0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x71, 0x0a, 0x10, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54,
	0x6f, 0x70, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x2e,
	0x54, 0x6f, 0x70, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x81, 0x01, 0x0a, 0x18, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x2e, 0x54, 0x6f, 0x70, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x6d, 0x61, 0x6e, 0x67, 0x52, 0x75, 0x73, 0x74,
	0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x6f, 0x70, 0x75, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_topup_topup_proto_rawDescOnce sync.Once
	file_topup_topup_proto_rawDescData []byte
)

func file_topup_topup_proto_rawDescGZIP() []byte {
	file_topup_topup_proto_rawDescOnce.Do(func() {
		file_topup_topup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topup_topup_proto_rawDesc), len(file_topup_topup_proto_rawDesc)))
	})
	return file_topup_topup_proto_rawDescData
}

var file_topup_topup_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_topup_topup_proto_goTypes = []any{
	(*FindByIdTopupRequest)(nil),             // 0: pb.topup.FindByIdTopupRequest
	(*FindMonthlyTopupStatus)(nil),           // 1: pb.topup.FindMonthlyTopupStatus
	(*FindYearTopupStatus)(nil),              // 2: pb.topup.FindYearTopupStatus
	(*FindMonthlyTopupStatusCardNumber)(nil), // 3: pb.topup.FindMonthlyTopupStatusCardNumber
	(*FindYearTopupStatusCardNumber)(nil),    // 4: pb.topup.FindYearTopupStatusCardNumber
	(*FindByCardNumberTopupRequest)(nil),     // 5: pb.topup.FindByCardNumberTopupRequest
	(*FindYearTopupCardNumber)(nil),          // 6: pb.topup.FindYearTopupCardNumber
	(*TopupResponse)(nil),                    // 7: pb.topup.TopupResponse
	(*TopupResponseDeleteAt)(nil),            // 8: pb.topup.TopupResponseDeleteAt
	(*ApiResponseTopup)(nil),                 // 9: pb.topup.ApiResponseTopup
	(*ApiResponseTopupDeleteAt)(nil),         // 10: pb.topup.ApiResponseTopupDeleteAt
	(*wrapperspb.StringValue)(nil),           // 11: google.protobuf.StringValue
}
var file_topup_topup_proto_depIdxs = []int32{
	11, // 0: pb.topup.TopupResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	7,  // 1: pb.topup.ApiResponseTopup.data:type_name -> pb.topup.TopupResponse
	8,  // 2: pb.topup.ApiResponseTopupDeleteAt.data:type_name -> pb.topup.TopupResponseDeleteAt
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_topup_topup_proto_init() }
func file_topup_topup_proto_init() {
	if File_topup_topup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topup_topup_proto_rawDesc), len(file_topup_topup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topup_topup_proto_goTypes,
		DependencyIndexes: file_topup_topup_proto_depIdxs,
		MessageInfos:      file_topup_topup_proto_msgTypes,
	}.Build()
	File_topup_topup_proto = out.File
	file_topup_topup_proto_goTypes = nil
	file_topup_topup_proto_depIdxs = nil
}
